run:
  timeout: 5m
  tests: false

linters:
  enable-all: true
  disable:
    - cyclop # complexity
    - depguard
    - dupl # cobra
    - gofumpt
    - err113
    - exhaustruct
    - gochecknoinits # cobra
    - gochecknoglobals # cobra
    - gocognit # complexity
    - funlen # complexity
    - lll
    - varnamelen

    - forbidigo # todo

    - tenv # deprecated

  fast: false
linters-settings:
  revive:
    rules:
      - name: unused-parameter
        arguments:
          - allowRegex: "cmd||args"

issues:
  exclude-files:
    - extract.*
    - cmd/dbgo_gen/run.go
    - cmd/dbgo_query/schema_copy.go
    - cmd/dbgo_query/schema_merger.go
    - cmd/dbgo_query/schema_jet.go
    - cmd/dbgo_query/schema_xstruct.go
